WIP
helium/rosetta-helium pull request #26
Opened 2021-10-01 22:02 UTC by jadeallenx

Problem to solve: We need to bundle and package the "rosetta" stuff into a consumable Docker build that is based on top of Ubuntu 18 because reasons.

2021-10-04 17:22 UTC, abhay commented
Heads up @syuan100. You're getting some help here.

2021-10-04 21:21 UTC, syuan100 requested changes

2021-10-04 21:21 UTC, syuan100 commented on Dockerfile
> +COPY . /src/rosetta
We can't copy from relative dir. We need this docker file to be able to run on its own due to deploy env reasons, that's why I had the git clone line.

2021-11-10 20:06 UTC, abhay commented on Dockerfile
> +ARG UBUNTU_RUNNER=quay.io/team-helium/blockchain-node:blockchain-node-ubuntu18-1.1.45
```suggestion
ARG UBUNTU_RUNNER=quay.io/team-helium/blockchain-node:blockchain-node-ubuntu18-1.1.46

```

2021-11-10 20:08 UTC, abhay commented on Dockerfile_testnet
> +ARG UBUNTU_RUNNER=quay.io/team-helium/blockchain-node:blockchain-node-testnet-ubuntu18-1.1.45
```suggestion
ARG UBUNTU_RUNNER=quay.io/team-helium/blockchain-node:blockchain-node-testnet-ubuntu18-1.1.46
```

2021-11-10 23:27 UTC, syuan100 commented
Will need to fix so there isn't a `COPY` from current dir, but this is good for now. Great job on this!

2021-11-10 23:27 UTC, merged